CREATE TABLE Usuario (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    SenhaHash VARCHAR(255) NOT NULL,
    Perfil VARCHAR(20) NOT NULL DEFAULT 'Garcom'
);

DROP TABLE Usuario;

SELECT * FROM Usuario;